name: React Native Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Instalar dependencias de Node.js
      - name: Install dependencies
        run: npm install

      # 4. Configurar el entorno de pruebas para React Native
      - name: Configure environment
        run: |
          npm install --save-dev @testing-library/react-native @testing-library/jest-native

      # 5. Ejecutar las pruebas
      - name: Run tests
        run: npm test -- --watchAll=false
